version: '3'

services:

  db:
    image: mysql
    container_name: mysql-crawler
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    #    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: news_crawler
#      MYSQL_DATABASE: cpd
#      MYSQL_USER: user1
#      MYSQL_PASSWORD: password1
    ports:
      - '3306:3306'
    volumes:
      - ../data/mysql/db:/var/lib/mysql
      - ../data/mysql/conf:/etc/mysql/conf.d
      - ./init/cpd.sql:/docker-entrypoint-initdb.d/init.sql:ro

  gui:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-crawler
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: news_crawler
      PMA_HOST: db
    ports:
      - '8080:80'

